apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.app.name }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
